---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: markov
  labels:
    app.kubernetes.io/name: markov
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: markov
  template:
    metadata:
      labels:
        app.kubernetes.io/name: markov
    spec:
      containers:
        - name: markov
          image: markov
          env:
            - name: GOWON_BROKER_HOST
              value: mosquitto
            - name: GOWON_MARKOV_CORPUS
              value: "markov:emma.txt"
            - name: GOWON_MARKOV_DATA_DIR
              value: /data
          volumeMounts:
            - name: corpus
              mountPath: /data
      volumes:
        - name: corpus
          configMap:
            name: corpus
