---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: markov
  labels:
    app.kubernetes.io/name: markov
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: markov
  template:
    metadata:
      labels:
        app.kubernetes.io/name: markov
    spec:
      initContainers:
        - name: init-file-wait
          image: alpine:latest
          command: ["sh", "-c", "while [[ ! -f /data/corpus.txt ]]; do echo waiting for corpus file; sleep 1; done"]
          volumeMounts:
            - name: markov
              mountPath: /data
      containers:
        - name: markov
          image: markov
          env:
            - name: GOWON_BROKER_HOST
              value: mosquitto
            - name: GOWON_MARKOV_CORPUS
              value: "markov:corpus.txt"
            - name: GOWON_MARKOV_DATA_DIR
              value: /data
          volumeMounts:
            - name: markov
              mountPath: /data
      volumes:
        - name: markov
          persistentVolumeClaim:
            claimName: markov
